In [1]:
wine = pd.read_csv("wine_pcv.csv")
wine.head(10)

,Unnamed: 0,price,main_country,main_variety,taster_name,norm_points,stand_points,points
0,1,15.0,Portugal,Portuguese Red,4,0.350000,-0.523700,87
1,2,14.0,US,Pinot Gris,5,0.350000,-0.748746,87
2,3,13.0,US,Riesling,19,0.636364,0.602494,87
3,4,65.0,US,Pinot Noir,5,0.350000,-0.748746,87
4,5,15.0,Spain,other,7,0.388889,0.042927,87
5,6,16.0,Italy,other,10,0.350000,-0.775196,87
6,7,24.0,France,Gewürztraminer,4,0.350000,-0.523700,87
7,8,12.0,Germany,Gewürztraminer,18,0.388889,-0.553896,87
8,9,27.0,France,Pinot Gris,4,0.350000,-0.523700,87
9,10,19.0,US,Cabernet Sauvignon,1,0.368421,-0.732593,87

In [2]:
np.corrcoef(wine["price"], wine["points"])[1,0]

0.4159800892237583

In [3]:
np.corrcoef(wine["price"], wine["norm_points"])[1,0], np.corrcoef(wine["price"], wine["stand_points"])[1,0]

(0.38553818585162186, 0.4056317989567191)

In [4]:
wine_ohe = pd.get_dummies(wine, prefix=['main_country', 'main_variety'])
one_hot1 = wine_ohe.drop(columns= ["Unnamed: 0", "taster_name", "price", "stand_points", "points"], axis=1)
one_hot2 = wine_ohe.drop(columns= ["Unnamed: 0", "taster_name", "price", "norm_points", "points"], axis=1)
one_hot3 = wine_ohe.drop(columns= ["Unnamed: 0", "taster_name", "price", "norm_points", "stand_points"], axis=1)
one_hot4 = wine_ohe.drop(columns= ["Unnamed: 0", "taster_name", "norm_points", "stand_points", "points"], axis=1)
one_hot4.head()

,price,main_country_Argentina,main_country_Australia,main_country_Austria,main_country_Chile,main_country_France,main_country_Germany,main_country_Italy,main_country_New Zealand,main_country_Portugal,...,main_variety_Rosé,main_variety_Sangiovese,main_variety_Sauvignon Blanc,main_variety_Sparkling Blend,main_variety_Syrah,main_variety_Tempranillo,main_variety_Viognier,main_variety_White Blend,main_variety_Zinfandel,main_variety_other
0,15.0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,14.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,13.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,65.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,15.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [6]:
#t Linear Regression
def linear_reg(dm_x, dm_y=wine[["price"]]):
    x_train, x_test, y_train, y_test = train_test_split(dm_x, dm_y, test_size=0.3, random_state=1)
    reg = linear_model.LinearRegression()
    reg.fit(x_train, y_train)
    predict_result = reg.predict(x_test)

    print("accuracy: "+ str(reg.score(x_test, y_test)*100) + "%")
    print("Mean absolute error: {}".format(mean_absolute_error(y_test, predict_result)))
    print("Mean squared error: {}".format(mean_squared_error(y_test, predict_result)))
    R2 = r2_score(y_test, predict_result)
    print('R Squared: {}'.format(R2))

    n=x_test.shape[0]
    p=x_test.shape[1] - 1
    adjusted_r_squared = 1 - (1 - R2) * ((n - 1)/(n-p-1))
    print('Adjusted R Squared: {}'.format(adjusted_r_squared))

In [7]:
linear_reg(one_hot1)

accuracy: 20.58494950751395%
Mean absolute error: 16.4467544959185
Mean squared error: 1321.232748462642
R Squared: 0.2058494950751395
Adjusted R Squared: 0.2047608381222562

In [8]:
linear_reg(one_hot2)

accuracy: 22.00489027817724%
Mean absolute error: 16.307491099068198
Mean squared error: 1297.6091124460015
R Squared: 0.22004890278177236
Adjusted R Squared: 0.2189797110106534

In [9]:
linear_reg(one_hot3)

accuracy: 22.05254279368183%
Mean absolute error: 16.276151971257427
Mean squared error: 1296.8163148133
R Squared: 0.22052542793681829
Adjusted R Squared: 0.21945688940764785

In [10]:
linear_reg(one_hot4, wine[["points"]])

accuracy: 24.54357876433485%
Mean absolute error: 2.1465845393167258
Mean squared error: 7.196040309341732
R Squared: 0.2454357876433485
Adjusted R Squared: 0.244401397346944